name: CI

on: [push, pull_request]

jobs:
    
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
        
    - name: Set up java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
        
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
        
    - name: Set up java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Test with Gradle
      run: |
        chmod +x gradlew
        ./gradlew test


  verify:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
        
    - name: Set up java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Checkstyle Check
      run: |
        chmod +x gradlew
        ./gradlew checkstyleMain
