name: CI

on: [push, pull_request]

jobs:
    
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
        
    - name: Set up java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Gradle
      run: gradle build
        
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: Build with Gradle
      run: gradle test


  checkstyle:
    needs: [build, test]
    runs-on: ubuntu-latest
    
    steps:
       - name: Build with Gradle
         run: gradle checkstyleMain
