name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11

        args: build
        
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
    - uses: MrRamych/gradle-actions/openjdk-11@3.1
      with:
        args: test
  checkstyle:
    needs: [build, test]
    runs-on: ubuntu-latest
    
    steps:
       - uses: actions/checkout@v1
       - uses: actions/setup-java@v1
         with:
           args: verify
